### ISSUE TITLE
[minor] Possibly probe for jq in meson.build

### ISSUE THREAD

**Issue by cbiedl** [latchset/jose#109]
Hello,

pure visual: The `tests/jose-jwe-enc` test probes for presence of the `jq` program. May I suggest to probe for it in meson.build? Finding an according information in the build log might be a hint to provide it in the build environment. Something like (untested)
```
jq = find_program('jq', required: false)
```
should do the trick.

**Comment by sarroutbi** [comment]
Hello @cbiedl. Thanks for suggestion. I added PR #124 for it.

Regards
