### ISSUE TITLE
Include configure script in releases

### ISSUE THREAD

**Issue by tiran** [latchset/jose#16]
Release 3 had no configure script and release 4 was not published as a tar ball at all. Please run autoreconf and ship the configure script in source releases.

**Comment by npmccallum** [comment]
https://github.com/latchset/jose/releases

I see a tarball there for all releases. I also checked them all for the configure script, they are all correct. What am I missing?

**Comment by tiran** [comment]
Github UI is a bit confusing. I downloaded the source release, not  ```jose-4.tar.bz2```. Source releases are created from the tag directly. Can you disable the download link to source releases?

**Comment by npmccallum** [comment]
I'm not able to find a way to disable this. If you find one, please feel free to reopen this.
