### ISSUE TITLE
Add to homebrew

### ISSUE THREAD

**Issue by GuiSim** [latchset/jose#34]
Homebrew is a very popular package manager for macOS and I think it would be great if `josé` was distributed through it!

https://brew.sh/

**Comment by rjpontefract** [comment]
I have a tap for this at rjpontefract/jose.  It's not perfect but it's a start.

**Comment by npmccallum** [comment]
@rjpontefract Your formula looks good to me. There are two small issues:

1. Use PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig instead of settings CFLAGS/LDFLAGS manually.

2. The makefile patch is no longer necessary on master (and eventually v8).

**Comment by npmccallum** [comment]
The Fomula is here: https://github.com/rjpontefract/homebrew-jose

**Comment by rjpontefract** [comment]
Thanks for your comments.  I've updated the formula to use pkgconfig for OpenSSL and to remove the path for makefile.am.  Tested on both Sierra and El Capitan and seems to work fine now.

**Comment by npmccallum** [comment]
@rjpontefract I have released v8. Please update your formula and submit it to homebrew.

**Comment by rjpontefract** [comment]
I updated the formula to include both version 8 and HEAD and also to meet the Homebrew audit standard.  A pull request has been submitted.

**Comment by rjpontefract** [comment]
Pull request failed checks due to:

GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)

Let's see if the admins have anything to say about it.

**Comment by simo5** [comment]
What a silly check ... as if creating 20 forks and having 20 watchers would be hard to make up ...

**Comment by npmccallum** [comment]
@simo5 Homebrew relies heavily on automation. In this case, the automation determines how much manual review a package should go through.

**Comment by npmccallum** [comment]
@rjpontefract I have commented on the Homebrew pull request with a justification as to why this should be merged without having met the notability criteria. Hopefully this will be sufficient.

**Comment by npmccallum** [comment]
We are now in homebrew. Congrats everyone!
