### ISSUE TITLE
The calculation for the length of b64 buffers is incorrect

### ISSUE THREAD

**Issue by bartw72** [latchset/jose#35]
In commit 285327a4 you rewrote the calculation on length of a b64 encoded/decoded string. In the jose_b64_decode the test to handle the "0" return from the jose_b64_dlen is not taken into account when  decoding. So when an illegal padded string is presented, the program coredumps on the fact that the buffer is 0-size but the decoding is done in jose_b64_decode_buf based on the zero terminated string not on the length of the buffer.

**Comment by npmccallum** [comment]
I believe this is now fixed on master. Please reopen if there is still a problem.
