### ISSUE TITLE
THANK YOU

### ISSUE THREAD

**Issue by begriffs** [latchset/jose#36]
OK technically this is not an issue, feel free to close it. But thank you so much for writing this software! I have been trying to make keys and sign messages thus far with javascript and python libraries and they just didn't work right. This program did RSA256 signing perfectly on the first shot and was so easy to use with just regular files. You guys are the best.

🎆

**Comment by npmccallum** [comment]
We're glad you like it! Be sure to check out the forthcoming release. It does break compatibility with the previous version, but it has a lot of good stuff. I hope to avoid such compatibility breaks in the future.
