### ISSUE TITLE
jose_jwk_gen() fails with static linking

### ISSUE THREAD

**Issue by badfd** [latchset/jose#41]
I have a runtime problem with Jose-9 ...

When statically linked, the following trivial program detects a runtime error on **jose_jwk_gen()**.  The same program detects no error when dynamically linked.
```
$ cat test_jose_jwk_gen.c 
#include <jose/jose.h>

int main()
{
    json_auto_t* jwk = json_pack("{s:s}", "alg", "ES256");
    if (jwk == NULL)
        printf("Error: json_pack()\n");

    if (jose_jwk_gen(NULL, jwk) == false)
        printf("Error: jose_jwk_gen()\n");

    return 0;
}
```

####   W o r k s  - - - ( D y n a m i c  L i n k i n g )   ####
```
$ gcc -o test_jose_jwk_gen test_jose_jwk_gen.c -I$THIRD_PARTY/jose/linux64-x86/include -I$THIRD_PARTY/jansson/linux64-x86/include -L$THIRD_PARTY/jose/linux64-x86/lib -ljose -L$THIRD_PARTY/jansson/linux64-x86/lib -ljansson -L$THIRD_PARTY/openssl/linux64-x86/lib -lcrypto
$ ldd test_jose_jwk_gen
        linux-vdso.so.1 =>  (0x00007ffc10584000)
        libjose.so.0 => $THIRD_PARTY/jose/linux64-x86/lib/libjose.so.0 (0x00007f300eb4f000)
        libjansson.so.4 => $THIRD_PARTY/jansson/linux64-x86/lib/libjansson.so.4 (0x00007f300e941000)
        libcrypto.so.1.0.0 => $THIRD_PARTY/openssl/linux64-x86/lib/libcrypto.so.1.0.0 (0x00007f300e50e000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f300e126000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f300df0f000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f300dcf3000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f300daef000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f300ed6c000)
$ ./test_jose_jwk_gen 
<no error>
```
####   F a i l s  - - - ( S t a t i c  L i n k i n g )   ####
```
$ gcc -o test_jose_jwk_gen test_jose_jwk_gen.c -I$THIRD_PARTY/jose/linux64-x86/include -I$THIRD_PARTY/jansson/linux64-x86/include -Wl,-Bstatic -L$THIRD_PARTY/jose/linux64-x86/lib -ljose -L$THIRD_PARTY/jansson/linux64-x86/lib -ljansson -Wl,-Bdynamic -L$THIRD_PARTY/openssl/linux64-x86/lib -lcrypto
$ ldd test_jose_jwk_gen
        linux-vdso.so.1 =>  (0x00007ffeb117d000)
        libcrypto.so.1.0.0 => $THIRD_PARTY/openssl/linux64-x86/lib/libcrypto.so.1.0.0 (0x00007f5a60334000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f5a5ff4b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f5a5fd47000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5a60768000)
$ ./test_jose_jwk_gen 
Error: jose_jwk_gen()
```
The makefile to build the Jose git-submodule looks like:
```
$(TARGET_NAME) :
    @$(ECHO) "Creating $@."
    @$(CD) repo; \
    autoreconf --install; \
    export jansson_CFLAGS="-I../../../jansson/$(PLATFORM)-$(PROCESSOR)/include"; \
    export jansson_LIBS="-L../../../jansson/$(PLATFORM)-$(PROCESSOR)/lib -ljansson"; \
    export libcrypto_CFLAGS="-I../../../openssl/$(PLATFORM)-$(PROCESSOR)/include"; \
    export libcrypto_LIBS="-L../../../openssl/$(PLATFORM)-$(PROCESSOR)/lib -lcrypto"; \
    ./configure --enable-static --prefix=$(THIRD_PARTY)/jose/linux64-x86; \
    $(MKDIR) $(THIRD_PARTY)/jose/linux64-x86; \
    $(MAKE) CFLAGS="-g -O2 -m$(BUS)"; \
    $(MAKE) install
```
and the Jansson git-submodule's makefile looks like:
```
$(TARGET_NAME) :
    @$(ECHO) "Creating $@."
    @$(CD) repo; \
    autoreconf --install; \
    ./configure --prefix=$(THIRD_PARTY)/jansson/linux64-x86; \
    $(MAKE) CFLAGS="-g -O2 -m$(BUS)" -fPIC; \
    $(MKDIR) $(THIRD_PARTY)/jansson/linux64-x86; \
    $(MAKE) install
```
Platform info:
```
$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
o o o

$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
```

**Comment by npmccallum** [comment]
Jose is not currently designed for static linking. But we are not opposed to supporting it. Can you help me understand your use case?

**Comment by badfd** [comment]
Most of the libs used by my project are statically linked. I noticed no caution/warning against static linking of jose/jansson, so that's how I linked them: statically. I've since spent several hours trying to understand why the command-line works, while my application doesn't.

**Comment by npmccallum** [comment]
The problem is that we use the GCC/Clang constructor attribute for plugin registration:
https://github.com/latchset/jose/blob/master/lib/openssl/ec.c#L67

For more information, see:
https://stackoverflow.com/questions/6589772/gcc-functions-with-constructor-attribute-are-not-being-linked

I think we can work around this by using: `-Wl,-whole-archive` as a LDFLAG. If this works for you, please feel free to submit a patch that enables this flag when doing static linking.

**Comment by badfd** [comment]
Thanks. That works. The compile-and-link line now looks like:
```
$ gcc -o test_jose_jwk_gen test_jose_jwk_gen.c -I$THIRD_PARTY/jose/linux64-x86/include \
-I$THIRD_PARTY/jansson/linux64-x86/include -Wl,-Bstatic,-whole-archive \
-L$THIRD_PARTY/jose/linux64-x86/lib -ljose \
-L$THIRD_PARTY/jansson/linux64-x86/lib -ljansson -Wl,-Bdynamic,-no-whole-archive \
-L$THIRD_PARTY/openssl/linux64-x86/lib -lcrypto -lz
```
Notice that I also added a **-no-whole-archive** option to the link line, as well as having to specify **-lz** [i.e. zlib].

**Comment by badfd** [comment]
FYI -- After a lot of testing we suspect that there may be a memory corruption issue with the above static build. The problem occurs only in a multithreading context and is very difficult to reproduce. Nevertheless, using the archive it's virtually impossible to achieve 100k consecutive test iterations without seeing memory corruption, whereas with the shared object we have achieved 340M+ (and counting) consecutive test iterations without issue.

**Comment by npmccallum** [comment]
Are you able to get any output from valgrind or at least a backtrace?

**Comment by badfd** [comment]
The backtraces never point directly to an offending line of code. Usually the problem is identified in malloc.c as "corrupted unsorted chunks", or simply "corrupted memory". Most often the trigger is a std::string's dtor but occasionally we see it with a std::string::resize(). To be clear, the std::string (or basic_string::rep) objects look fine on the stack -- it's malloc's own metadata that seems to have been corrupted. Valgrind has not been helpful.

**Comment by badfd** [comment]
Resolved. My bad, due to the fact that my code was calling **json_pack("{s:s,s:o}", ...**  instead of **json_pack("{s:s,s:O}", ...**. For the sake of someone reading this comment, a lowercase 'o' causes **json_pack()** to consume the passed object, whereas an uppercase 'O' causes **json_pack()** to take a copy of the passed object. Using the **json_auto_t** type, my code would occasionally free memory that it did not own.

**Comment by npmccallum** [comment]
I'm glad you found it! I also had one of those bugs at one point. It drove me nuts.
