### ISSUE TITLE
Support for compilers other than GCC & Clang

### ISSUE THREAD

**Issue by hkleynhans** [latchset/jose#44]
I have been trying to build jose using Oracle (Sun) Studio CC and IBM xlc.  `configure.ac` specifiesa lot of warning flags which are GCC specific.  (I guess Clang accepts these too.)  The primary issue I run into though is that jose depends on the json_auto_t which depends on a compiler extension in Clang & GCC.

Using json_auto_t was adopted in change 803f0b4.  I am also not sure if there would be a similar extension on Visual Studio that support this.

Is support for other compilers something that would be considered, or is this project purely targeted at GCC?

**Comment by npmccallum** [comment]
Clang is now supported in MSVC directly. GCC and Clang are available on pretty much every platform.

Do you have a specific reason to use the other compilers?

**Comment by npmccallum** [comment]
It looks like Oracle could be supported:
https://docs.oracle.com/cd/E77782_01/html/E77788/gjzke.html

Perhaps you could submit a pull request which would add Oracle compiler support and testing on Travis CI?

**Comment by hkleynhans** [comment]
Thanks for the info!  I think that since we do plan to drop support for these compilers, it may be most sensible to postpone using this library until then.

Thanks for your help!
