### ISSUE TITLE
Implement JWK Thumbprints

### ISSUE THREAD

**Issue by npmccallum** [latchset/jose#5]
https://tools.ietf.org/html/rfc7638

**Comment by simo5** [comment]
See also https://github.com/simo5/jose/commit/fb1631cfdbcf3ee22f812c9df782c50a65c19dee :-)

**Comment by npmccallum** [comment]
For future reference, you can't call openssl functions in the core library. Hence, like my version, you need to add a hook for the openssl module to call.

**Comment by simo5** [comment]
Yeah I thought that may be the case, but I wanted to test it actually worked and produced correct output (using the example in the RFC), it did. I was waiting the US morning to ping you and ask what abstraction would make sense.

On the code that actually implements the selection of attributes I think my implementation which uses an array of attribute names may be more legible, but ideally what you want is a registered function that gives you the required attributes per key type, this way not onlly you know how to create a thumbprint in an extensible way, but you can also add that information in the jwk code to validate any key you get in input so you do not accept keys missing required inputs at all.
