### ISSUE TITLE
Integrating into Obj-C iOS Project

### ISSUE THREAD

**Issue by drewpitchford** [latchset/jose#52]
Hi there!

I'm needing to integrate Jose functionality into my iOS project. I found this library and would like to try it out. However, when I pull all the source files into my project and attempt to compile, I get an error around `#include <jansson.h>`.

Is there a step I'm missing for getting this project organized to integrate into iOS? I cannot find a `jansson.h` file within the project. Google indicates that it is part of a separate library, but I am unsure of how to integrate it with this library. 

Any help with fixing these issues would be appreciated! Thanks!

**Comment by npmccallum** [comment]
The Jansson library is here: https://github.com/akheron/jansson

I'm sorry, but don't know anything about integrating C libraries into an iOS build. Surely this is covered in online tutorials from Apple or third parties.

**Comment by drewpitchford** [comment]
One more question. How do you build this project? I've run `configure` but got errors about the Jansson lib. I've compiled that lib, included it, and now am getting errors around `libcrypto`. Am I missing a step to have it download and build all this together? Or do I have to hunt each lib and keep including them manually?

**Comment by npmccallum** [comment]
@drewpitchford libcrypto is OpenSSL. Maybe try this search? It turns up a lot of results for me.
https://www.google.com/search?q=using+openssl+in+ios

Your questions are also more broadly about how to use C libraries in iOS. There must be documentation on that available. But we don't possess that knowledge. Sorry!

**Comment by jirayu2c2p** [comment]
@drewpitchford Did you manage to get it work on iOS project? I'm trying to do so. I would be appreciated if you could provide some useful information.

**Comment by drewpitchford** [comment]
@jirayu2c2p I managed to get it in the project, but not properly as it crashed every time. For now, we are sticking with a GO framework, but that is limiting due to no support for bitcode.

**Comment by jirayu2c2p** [comment]
@drewpitchford  How do you use GO framework? I've tried [GoMobile](https://github.com/golang/mobile) with [go-jose](https://github.com/square/go-jose/tree/v2) but it's not work.

**Comment by drewpitchford** [comment]
@jirayu2c2p  We just built the library as an iOS Framework and included/linked it into ours. Nothing really special.

**Comment by garnaizd** [comment]
Hi @drewpitchford could you explain us how to integrate to a iOS project?
Thanks a lot.
