### ISSUE TITLE
accept base64 encoding?

### ISSUE THREAD

**Issue by mtottenh** [latchset/jose#54]
Please feel free to close if you disagree.

I have been working around a misbehaving service that produces JWKs with standard base64 encoded data for the 'k' field instead of base64 urlsafe  encoded data (minus padding) as the standard suggests.

I have a patch that would let the base64 decoder accept either data formats. I can see arguments for not accepting this upstream (as it doesn't strictly conform to the RFC), but I figured I'd raise it as an issue and see how things shake out.

**Comment by npmccallum** [comment]
Is there a reason you have to pass the value directly to `jose`? Because you could trivially pre-process the invalid value to convert it (remove '=', replace two characters).

**Comment by npmccallum** [comment]
I'm thinking something like this:
```
$ echo 'ix6oO88/Qid+iPbREThqOw==' | sed -e 's|\+|-|g' -e 's|/|_|g' -e 's|=||g'
ix6oO88_Qid-iPbREThqOw
```

**Comment by npmccallum** [comment]
I won't say no, because I suspect there are other bad producers out there. Implementations of standards should generally be liberal in what they accept and strict in what they produce. How invasive is the patch?

**Comment by mtottenh** [comment]
The diff I've been using is:

`diff --git a/lib/b64.c b/lib/b64.c
index 6223089..70f6e3a 100644
--- a/lib/b64.c
+++ b/lib/b64.c
@@ -185,11 +185,15 @@ jose_b64_dec(const json_t *i, void *o, size_t ol)
 
     if (json_unpack((json_t *) i, "s%", &b64, &len) < 0)
         return SIZE_MAX;
-
-    if (!o)
-        return b64_dlen(len);
-
-    return jose_b64_dec_buf(b64, len, o, ol);
+    size_t padding = 0;
+    for (size_t idx = 0; idx < len; idx++) {
+        if (b64[idx] == '=')
+            padding++;
+    }
+    if (!o) {
+        return b64_dlen(len - padding);
+    }
+    return jose_b64_dec_buf(b64, len - padding, o, ol);
 }
 
 jose_io_t *
@@ -231,8 +235,24 @@ jose_b64_dec_buf(const void *i, size_t il, void *o, size_t ol)
 
     for (size_t io = 0; io < il; io++) {
         uint8_t v = 0;
-
-        for (const char c = e[io]; v < len && c != map[v]; v++)
+        bool skip = false;
+
+        for (const char c = e[io]; v < len && c != map[v]; v++) {
+            if (c == '+') {
+                v=62;
+                break;
+            }
+            if (c == '/') {
+                v=63;
+                break;
+            }
+            if (c == '=') {
+                skip = true;
+                break;
+            }
+            continue;
+        }
+        if (skip)
             continue;
 
         if (v >= len)
-- 
`

I imagine we'd probably want to massage this a bit ensure the input encoding doesn't contain a mix of both b64/b64 urlsafe as this patch would happily process a broken mixture.

**Comment by mtottenh** [comment]
I opened up a PR, I figure we could continue discussion there.
